# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jalaziz.io
title: Frustrations of a Software Engineer
author: Jameel Al-Aziz
#simple_search: http://google.com/search
description: Frustrations of a Software Engineer

# RSS / Email (optional) subscription links (change if using something like Feedburner)
email: me@jalaziz.io
subscribe_rss: http://feeds.feedburner.com/jalazizio

include: .well-known

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /blog/:year/:month/:day/:title/
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: true

paginate: 10          # Posts per page on the blog index
paginate_path: blog/page/:num  # Directory base for pagination URLs eg. /blog/page/2/

exclude_from_sitemap: [/atom.xml, /sitemap.xml]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: jalaziz
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Disqus Comments
disqus_short_name: jalaziz-io
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-46386911-1

# Facebook Like
facebook_like: true

gravatar_url: http://www.gravatar.com/avatar/a1b6e156df63325a701e6143e452e3e0.png

linkedin_public_url: http://www.linkedin.com/in/jalaziz

gittip_user: jalaziz

bitcoin_address: 1MdXAAYx1a16Atij8PHYK5yH6XNXExzNEo
bitcoin_amount: $10
